### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by CHENzQIANG** [bootsrc/jseckill#10]
1.大佬问一下支付功能怎么体现，我在输入手机号后秒杀成功，然后也没有支付界面，mysql中库存也没变。。。
2.大佬，Jemeter怎么传不同的手机号啊。。。

**Comment by liushaoming** [comment]
谢谢支持。 
回答问题1： 
我这里只有秒杀功能，没有支付功能，因为支付功能可以再抢到后30分钟内支付；
相对秒杀过程来说，并发没那么高。处理相对常规，不是这个开源项目的重点，只需要按照支付api开发即可。

回答问题2：
你可以搜索一下jmeter怎么传送动态参数，我没有做过。  如果jmeter无法实现，你可以自己用java代码来模拟登陆和秒杀过程，使用多线程和线程池。
