### ISSUE TITLE
请问为什么updateInventory没有函数调用他

### ISSUE THREAD

**Issue by zhangyu1402** [bootsrc/jseckill#11]
请问你项目中什么时候会修改mysql？感觉流程截止在了redis中inventory减一

**Comment by bootsrc** [comment]
是的。在readme里有说明。这个项目里只做里抢的过程。并没有做支付和数据库里的减库存。
就像12306抢票一样。 抢到后redis里给保留30分钟， 只有付款后，数据库里的库存才会真正减少。
后面支付和mysql减库存，并发量较小，不属于秒杀的重点，所以这里并没有去实现这个步骤。
